# Generated by Django 4.2.11 on 2024-03-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.BooleanField(choices=[(True, 'completed'), (False, 'pending')], default=False),
        ),
    ]
