# Generated by Django 4.2.11 on 2024-03-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('peding', 'pending')], default=False, max_length=10),
        ),
    ]
