# Generated by Django 4.2.11 on 2024-03-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todoitem_created_at_todoitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.todoitem'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
